### ISSUE TITLE
資料集計劃下的檔案若為PDF 無法於內嵌開啟

### ISSUE THREAD

**Issue by allycat** [depositar-io/ckanext-data-depositario#1]
如標題，不管在chrome or firfox 都有相同問題，內嵌無法開啟PDF ，但若於另開視窗則可以。

**Comment by u10313335** [comment]
感謝回報。發生錯誤時若回到上一頁會在上方顯示以下錯誤訊息：

```
Could not proxy resource because a connection error occurred. [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

經查為 Python requests library 的問題，改安裝 requests[security] 版本即可。現已修復。

ref: https://stackoverflow.com/questions/10667960/python-requests-throwing-sslerror
